### ISSUE TITLE
Implement Error Boundaries

### ISSUE THREAD

**Issue by baileydunning** [kiddo-capstone/kiddo-frontend#30]
https://reactjs.org/docs/error-boundaries.html

**Comment by baileydunning** [comment]
https://www.npmjs.com/package/react-error-boundary#errorboundary-props

**Comment by brabbuss** [comment]
Awesome, here's that Medium article you linked in the PR too: https://medium.com/thinking-design/how-to-write-design-user-friendly-error-messages-87d0207bb902
