### ISSUE TITLE
Styling Tools Workflow: Question 

### ISSUE THREAD

**Issue by lo-la-do-li** [kiddo-capstone/kiddo-frontend#31]
I was having an issue implementing a consistent styling to the SideBar component,
trying to incorporate material-ui's makeStyles() prop and our own styles theme in state (ui/common/theme). 

What are your thoughts/preferences? 

Solution #1:
- Accessing our theme in global state with:
- - `const [state, dispatch] = useContext(AppContext)` 
and then applying inline styles with: 
- - `<someElement style={{backgroundColor:`${state.theme.colors.primary}`}></someElement>`

Solution #2: 
- Call our theme styles inside of makeStyles() by importing the theme into the component, and setting to a variable (appStyles in this example)

![Screen Shot 2021-02-21 at 2 03 32 PM](https://user-images.githubusercontent.com/68264128/108638714-b4d39100-744d-11eb-8ee0-d13f69ff0454.png)

**Comment by brabbuss** [comment]
@lo-la-do-li I'm not sure which is a simpler flow practically, but I do like the idea of keeping away from inline styling as much as possible with option 2

**Comment by brabbuss** [comment]
I like what you did with the theme context, so I'll clise the issue out!
